all:
	make -C testprotoc
	make -C clientlike
	make -C dbserverlike
	make -C fightserverlike
	make -C logicserverlike
	make -C rankserverlike
clean:
	make -C testprotoc clean
	make -C clientlike clean
	make -C dbserverlike clean
	make -C fightserverlike clean
	make -C logicserverlike clean
	make -C rankserverlike clean
