LIBFILE = libserver.a
include ../makerule/makefile.depend
INC_ALL += ${INC_NET} ${INC_LIBCURL} ${INC_ASYNC_WORK} ${INC_UTILITY} ${INC_JSON}
LIB_ALL += ${LIB_NET} ${LIB_LIBCURL} ${LIB_ASYNC_WORK} ${LIB_UTILITY}
include ../makerule/makefile.rule
